name: Get Activation File
on: workflow_dispatch
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-request-activation-file@v2
        with:
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: activation-file
          path: ./*.alf